### ISSUE TITLE
nglview not working

### ISSUE THREAD

**Issue by thempel** [markovmodel/pyemma-workshop#11]
notebook 05-pcca-tpt, function `visualize_metastable(my_samples, cmap, selection='backbone')` does not yield any output (tested on a macbook). Can anyone confirm? 

@fabian-paul We should maybe delete this function from the notebook as nglview tends to be extremely unstable.

**Comment by clonker** [comment]
while i tried running the NB this morning, it was lacking a model checkpoint (`pyemma.load('nb4.pyemma', model_name='doublewell_msm')`). can you direct me to where these files are?

**Comment by thempel** [comment]
Thanks for testing. This file is generated in notebook 4, I copied my version to `/group/ag_cmb/scratch/thempel/share/` for your convenience.

**Comment by clonker** [comment]
can confirm, also on my machine (arch linux) nglview does not show up :-1:

**Comment by marscher** [comment]
The installation method of nglview sucks, but the viewer itself is stable and widely used. This discussion comes up every time some tries to mix pypi vs. conda installations of nglview. There are tons of proposed solutions, which one needs to iterate through. In the end it is always a leftover from an old install.

**Comment by clonker** [comment]
What can I say.. doesn't get much cleaner in terms of install than shiny new conda environment + conda-forge only. No pypi vs conda mixing and also calling `jupyter-nbextension enable nglview --py --sys-prefix` fixed it for me, so in this case it was not a leftover from an old install but rather the extension not activating properly. For sure once it runs it runs stable but the installation procedure itself is horrendous IMO.

**Comment by clonker** [comment]
Begs the question, how do we want to deal with this in the workshop? For sure it is a nice to have and improves the user experience if they are able to visualize what they are doing directly in molecule space. If possible I'd keep it in the notebooks.

**Comment by thempel** [comment]
We can tell people that it sometimes works, sometimes doesn't... I'd leave the decision to @fabian-paul as he is responsible for this particular tutorial. 

Actually, in my case it isn't even an issue with an old installation since that's really the first installation of nglview on that machine. `jupyter-nbextension enable nglview --py --sys-prefix` fixed it.

**Comment by hainm** [comment]
> jupyter-nbextension enable nglview --py --sys-prefix fixed it.

> The installation method of nglview sucks, but the viewer itself is stable and widely used. 

This is the way how jupyter-based widgets works in general and you all should get used to it. 
There are just 2 lines of instruction how to install `nglview`, and if you follow that, it should work.
If you don't follow that and blame "sucks", I think it's not unfair for `nglview`. 

https://github.com/arose/nglview#released-version

**Comment by clonker** [comment]
I understand you are frustrated and please excuse the strong language. It is however the only widget that I know of and regularly use which does not work "out of the box" after a conda install (which imo should be the expected behavior).
If nglview is to blame for this or the way ipywidgets are installed in general I cannot comment on.

**Comment by fabian-paul** [comment]
nglview works for me. So no problem with the TPT tutorial at least on the teacher's side. :-)

**Comment by marscher** [comment]
@thempel it does not matter if it is a new machine, because a pip install placed its files inside your home directory.
@hainm Is this command not invoked automatically anymore upon a conda install?

**Comment by hainm** [comment]
@marscher you are the maintainer of `nglview` conda. ;)

https://github.com/conda-forge/nglview-feedstock

**Comment by marscher** [comment]
Even our sophisticated install method in the conda recipe does not supersede an installation outside of the conda environment. If I remember correctly I raised an issue in jupyters notebooks repo about this.
