### ISSUE TITLE
transition probability matrix between the metastable states

### ISSUE THREAD

**Issue by Wencesgiovanni** [markovmodel/pyemma-workshop#23]
I have calculated the transition matrix of a Markov state model with four metastable states. Also I have calculated the probability of transition between metastable states, for which I obtain a 4x4 matrix.

nstates = 4
transition_matrix_meta = np.zeros((nstates, nstates))

for i in range(nstates):
    for j in range(nstates):
        pi_i = msm.pi[msm.metastable_sets[i]].sum()
        T_i_to_j = msm.transition_matrix[msm.metastable_sets[i]][:, msm.metastable_sets[j]]
        P_i_to_j = pi_i * T_i_to_j.sum()
        
        transition_matrix_meta[i, j] = P_i_to_j

# Normalize the rows
transition_matrix_meta = transition_matrix_meta / transition_matrix_meta.sum(axis=1, keepdims=True)

print(transition_matrix_meta)

Results that the probabilities of transition between differents  metaestables states are relatively small, for example, 
0.014320,  0.000000 , 0.021200  and in the diagonal the probabilities are closed to 1, this is commun? why?

**Comment by clonker** [comment]
yes, this is commun when you have metastable processes :)

**Comment by Wencesgiovanni** [comment]
clonker, what is the argument? Thanks

**Comment by clonker** [comment]
metastability (intuitively) means that you stay in one state for a long time and then switch to another, just to stay there for a long time. if you have a diagonally dominant transition matrix, it is confirming exactly that intuition.

**Comment by Wencesgiovanni** [comment]
Dear clonker, thank you very much.

**Comment by clonker** [comment]
closing this issue then, feel free to reopen if something remains unclear!
