### ISSUE TITLE
use git object (tag, branch) for workshops dates (e.g. 2018_1)

### ISSUE THREAD

**Issue by marscher** [markovmodel/pyemma-workshop#5]

**Comment by cwehmeyer** [comment]
Why not use releases, e.g., 2018_1, ...?

**Comment by marscher** [comment]
If a workshop release is an ancestor of the previous one, this makes also sense.

**Comment by cwehmeyer** [comment]
I think we will rather build on existing material than creating a completely new set of files.

**Comment by marscher** [comment]
So we can just tag the 2018 version and go on with the new one (which will presumably only contain extended material to the existing notebook tutorial paper, right?)

**Comment by cwehmeyer** [comment]
Yes, let's do that.
